---
title: "9-SiteYearHandover"
author: "Galina M. Jönsson"
date: "15/09/2021"
output: html_document
---

## All sites and site:year combinations
```{r site-numbers-A-urticae, message=FALSE, warning=FALSE, echo=FALSE}
occDetdata <- read.csv("../data/formattedData/occDetdata_merged_2020-04-07.csv", 
                       header=T, na.strings=c("","NA")) 
spp_vis <- read.csv("../data/formattedData/spp_vis_merged_2020-04-07.csv", 
                    header=T, na.strings=c("","NA"))



#occDetdata <- subset(occDetdata, TP<=76 & TP>=61)
#spp_vis2 <- spp_vis[,c("visit", 'Aglais.urticae')]
#spp_vis2 <- subset(spp_vis2, visit %in% occDetdata[occDetdata$visit,])


#occDetdata$TP <- findInterval(occDetdata$TP, seq(61,76, 2))
#occDetdata$TP3 <- findInterval(occDetdata$TP, seq(61,76, 3))
#occDetdata$TP4 <- findInterval(occDetdata$TP, seq(61,76, 4))
#occDetdata$TP5 <- findInterval(occDetdata$TP, seq(61,76, 5))
#occDetdata$TP6 <- findInterval(occDetdata$TP, seq(61,76, 6))
#occDetdata$TP7 <- findInterval(occDetdata$TP, seq(61,76, 7))
#occDetdata$TP8 <- findInterval(occDetdata$TP, seq(61,76, 8))
#occDetdata$TP9 <- findInterval(occDetdata$TP, seq(61,76, 9))
#occDetdata$TP10 <- findInterval(occDetdata$TP, seq(61,76, 10))


source("./function-DT.overlap.R")


A_urticae <- DT.overlap(taxon_name = 'Aglais.urticae',
                         occDetdata = occDetdata,
                         spp_vis = spp_vis,
                         modeltype = "mixlistlength",
                         minTP = 61, 
                         maxTP = 76,
                         TPinterval = 10)


A_urticae8$overlap["1-3", "sites"]
A_urticae8$overlap["1-3", "site_TPs"]

#$overlap
#    sites site_TPs TPs
#1-2     0        0   0
#1-3    22       13   2
#2-3     0        0   0



### BNM
#length(unique((subset(occDetdata, L <200))$site))
### 1320

### UKBMS
#length(unique((subset(occDetdata, L == 22222))$site))
### 0

### NHM
#length(unique((subset(occDetdata, L == 33333))$site))
### 471
```


```{r site-numbers-A-urticae, message=FALSE, warning=FALSE, echo=FALSE}

spp_vis <- read.csv("../data/formattedData/spp_vis_merged_2020-04-07.csv", header=T, na.strings=c("","NA"))

visitDat <- merge(occDetdata, spp_vis[, c("visit",
                              'Aglais.urticae',
               'Carterocephalus.palaemon',
               'Erebia.aethiops',
               'Erebia.epiphron',
               'Limenitis.camilla',
               'Lycaena.phlaeas',
               'Melitaea.athalia',
               'Pararge.aegeria',
               'Pieris.rapae',
               'Polygonia.c.album',
               'Polyommatus.bellargus',
               'Thecla.betulae')], 
      by= "visit", all.x = T, all.y = F)




#################################################### 
#################  Aglais urticae  ################# 
#################################################### 


#nrow(subset(visitDat, Aglais.urticae == TRUE))
# 1070 visits

### BNM
length(unique((subset(subset(visitDat, Aglais.urticae == TRUE), L <200))$site))
### 489

### NHM
length(unique((subset(subset(visitDat, Aglais.urticae == TRUE), L == 33333))$site))
### 45

### overlap
length(unique((subset(subset(visitDat, Aglais.urticae == TRUE), L == 33333))$site)[unique((subset(subset(visitDat, Aglais.urticae == TRUE), L == 33333))$site) %in% unique((subset(subset(visitDat, Aglais.urticae == TRUE), L <200))$site)])
### 22


### BNM
length(unique((subset(subset(visitDat, Aglais.urticae == TRUE), L < 2000))$siteYear))
### 720

### NHM
length(unique((subset(subset(visitDat, Aglais.urticae == TRUE), L == 33333))$siteYear))
### 45

### overlap
length(unique(subset(visitDat, Aglais.urticae == TRUE & L == 33333)$siteYear)[unique((subset(subset(visitDat, Aglais.urticae == TRUE), L == 33333))$siteYear) %in% unique((subset(subset(visitDat, Aglais.urticae == TRUE), L <200))$siteYear)])
### 0 !!!!!!



#################################################### 
###########  Carterocephalus palaemon  ############# 
#################################################### 

#nrow(subset(visitDat, Carterocephalus.palaemon == TRUE))
# 16 visits


### BNM
length(unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L <200))$site))
### 8

### NHM
length(unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L == 33333))$site))
### 5

### overlap
length(unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L == 33333))$site)[unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L == 33333))$site) %in% unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L <200))$site)])
### 0


### BNM
length(unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L < 2000))$siteYear))
### 0

### NHM
length(unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L == 33333))$siteYear))
### 0

### overlap
length(unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L == 33333))$siteYear)[unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L == 33333))$siteYear) %in% unique((subset(subset(visitDat, Carterocephalus.palaemon == TRUE), L <200))$siteYear)])
### 0 !!!!!!


```